# assignment on Group by 
#1. Retrieve the total revenue generated for each film category.
select ca.name,sum(p.amount) from category ca
join film_category fc on ca.category_id=fc.category_id
join film f on fc.film_id=f.film_id
join inventory i on fc.film_id=i.film_id
join rental r on i.inventory_id=r.inventory_id
join payment p on r.rental_id=p.rental_id
group by ca.name

#2. Determine the count of rentals for each customer.
select c.first_name,count(r.rental_id) as TotalRental from rental r
join customer c on r.customer_id=c.customer_id
group by c.customer_id
order by c.first_name

#3. Calculate the average rental duration (in days) for each film.
select film_id,avg(rental_duration) from film
group by film_id

#4. Find the total revenue generated for each month.
select date_format(payment_date,'%m') as months, sum(amount)
from payment
group by months
order by months

#5. Determine the total revenue generated by each store.
select s.store_id ,sum(p.amount) from 
store s join staff st on s.store_id=st.store_id
join rental r on st.staff_id=r.staff_id
join payment p on r.staff_id=p.staff_id
group by p.amount 

#6. Calculate the count of rentals handled by each staff member.
select st.staff_id ,count(r.rental_id) from
staff st join rental r on st.staff_id= r.staff_id
group by st.staff_id
order by st.staff_id

#7 Compute the average rental rate for each film category.
select ca.name,avg(f.rental_rate)
from category ca
join film_category fc on ca.category_id=fc.category_id
join film f on fc.film_id=f.film_id
group by ca.name


#8. Determine the count of rentals for each film.
SELECT f.title AS film_title, COUNT(r.rental_id) AS rental_count
FROM rental r
JOIN inventory i ON r.inventory_id = i.inventory_id
JOIN film f ON i.film_id = f.film_id
GROUP BY f.title
ORDER BY rental_count DESC;

#9. Retrieve the total revenue generated for each city.
select ct.city, sum(p.amount)
from city ct join address ad on ct.city_id=ad.city_id
join staff st on ad.address_id=st.address_id
join payment p on st.staff_id=p.staff_id
group by ct.city


#10. Calculate the count of rentals for each film language.
select  l.name ,count(r.rental_id)
from rental r
join inventory i on r.inventory_id = i.inventory_id
join film f on i.film_id = f.film_id
join language l on f.language_id = l.language_id 
group by l.name
order by l.name;

